[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pycparser"
version = "2.21"
description = "A C parser and AST generator written in pure Python"
